### ISSUE TITLE
One-shot geolocation updates

### ISSUE THREAD

**Issue by anssiko** [WICG/geolocation-sensor#5]
The [one-shot geolocation updates][1] requirement is addressed by [`getCurrentPosition()`][2] in the Geolocation API.

Define a modernized version of this convenience method that returns a promise. Add it either to the [`Sensor`][3] interface if deemed generic or to the derived [`GeolocationSensor`][4] if considered a special case.

See https://github.com/w3c/sensors/issues/88

[1]: https://www.w3.org/TR/geolocation-API/#req_oneshot
[2]: https://www.w3.org/TR/geolocation-API/#get-current-position
[3]: https://w3c.github.io/sensors/#the-sensor-interface
[4]: https://wicg.github.io/geolocation-sensor/#geolocationsensor

**Comment by martijnthe** [comment]
I like [this solution](https://github.com/w3c/sensors/issues/88#issuecomment-193002528) that was mentioned in that thread.

**Comment by anssiko** [comment]
I'm getting signals from the broader community this feature should be prioritized higher. I labeled this issue as P1.

**Comment by alexshalamov** [comment]
@anssiko this looks like a generic feature. We will check with @pozdnyakov what is the impact for API surface and propose few options.

**Comment by anssiko** [comment]
@alexshalamov, thanks for volunteering!

**Comment by kenchris** [comment]
We got the same exact feedback from the Ionic Framework guys and their new Capacitor project. If they were to move to the new API, the top missing feature is the one shot

**Comment by kenchris** [comment]
I think a solution like that mentioned by @martijnthe is fine

```Geolocation.read({ accuracy: "high" }).then(reading => findAddress(reading.coords));```

It would basically be a static method, thus not requiring you to instantiate the object, and you provide the SensorOptions as an optional parameter (probably a limited one as "frequency" doesn't make any sense here).

Any failure will result in a rejected promise. It also works fine with async await

```
async function findAddress() {
   const _findAddress(coords) => ... 

   const reading = await Geolocation.read({accuracy: "high"});
   return _findAddress(reading.coords);
}
```

But as we have no stop, we need a way to cancel, thus using the AbortController: 
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://developers.google.com/web/updates/2017/09/abortable-fetch

```

async function findAddress(timeout) {
  const controller = new AbortController();
  const signal = controller.signal;

  setTimeout(() => controller.abort(), timeout);

  const reading = await Geolocation.read({ accuracy: "high", signal });
  ...
  return address;
}
```
