### ISSUE TITLE
Need [SecureContext] to match Sensor

### ISSUE THREAD

**Issue by foolip** [WICG/geolocation-sensor#8]
https://wicg.github.io/geolocation-sensor/#api

This interface inherits from Sensor, which has [SecureContext]:
https://w3c.github.io/sensors/#api

**Comment by anssiko** [comment]
@foolip, thanks for the feedback!

I submitted a fix https://github.com/WICG/geolocation-sensor/pull/9 and opened https://github.com/w3c/sensors/issues/313 to track changes to all derived interfaces.
